### ISSUE TITLE
Error Class not Found

### ISSUE THREAD

**Issue by notabigboy** [chapcz/admin-sandbox#1]
`Error Class 'Doctrine\Common\Persistence\AbstractManagerRegistry' not found`

`File: ...\nettrine\orm\src\ManagerRegistry.php:12`

**Comment by chapcz** [comment]
Updated dependencies. This should fix your problem. 

https://forum.nette.org/cs/33442-pozor-na-nove-verze-doctrine-common-3-0-0-nekompatibilni-s-nettrine#p210803
